# Generated by Django 2.1.3 on 2018-11-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_alias', models.CharField(max_length=128)),
                ('ca_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('itp_user_id', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('plb', models.CharField(max_length=128)),
                ('cs_name', models.CharField(max_length=128)),
            ],
        ),
    ]
