# Generated by Django 2.1.3 on 2018-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='app_flag',
            field=models.SmallIntegerField(choices=[(0, 'WX'), (1, 'Line')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='cs_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
