# Generated by Django 2.1.3 on 2018-11-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlserver', '0002_auto_20181122_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=256)),
                ('answers', models.CharField(max_length=300)),
                ('key_words', models.CharField(max_length=128)),
            ],
        ),
    ]
